export const FETCH_STORE_REQUEST = "FETCH_STORE_REQUEST";
export const FETCH_STORE_SUCCESS = "FETCH_STORE_SUCCESS";
export const FETCH_STORE_ERROR = "FETCH_STORE_ERROR";
export const UPDATE_STORE_LIST = "UPDATE_STORE_LIST";
